# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_history_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='music_history_api.Artist'),
        ),
    ]
